### ISSUE TITLE
bad css property

### ISSUE THREAD

**Issue by iiinsomnia** [iocave/customize-ui#10]
![image](https://user-images.githubusercontent.com/6582246/68672623-f4de6f80-058c-11ea-9330-fc35c979a1a9.png)

![image](https://user-images.githubusercontent.com/6582246/68672670-0d4e8a00-058d-11ea-90f6-45e11be48ec9.png)

**Comment by knopp** [comment]
Thank you. I'm not quite sure why the rule was there. You can try updating to 0.1.24 (just pushed) and let me know if it works for you.

**Comment by iiinsomnia** [comment]
It works OK ! 👍
