### ISSUE TITLE
Position of Traffic Lights Glitches When Switching Files

### ISSUE THREAD

**Issue by phendan** [iocave/customize-ui#114]
Since one of the recent updates to VS Code, with the title bar set to 'inline', the traffic lights briefly flicker out of position and then fix themselves whenever I switch files. This happens whether I choose them from the sidebar or via cmd+p. I'll provide a screen recording of the effect. Maybe also worth noting: when I reload the window from the command palette, the icons also glitch and then stay glitched until I edit or save the current file.

Would be awesome if you could find a fix for this. I love the look and flexibility this extension provides, so keep up the great work!

https://user-images.githubusercontent.com/10546560/142730457-87579bb9-7d99-4da0-a8f9-0efebcfa581a.mp4

.

**Comment by knopp** [comment]
Can you please confirm that this persists once `0.1.55` is online? (should be within an hour)

**Comment by phendan** [comment]
Oh wow, updating to `0.1.55` does indeed seem to have fixed it. Thanks a bunch!

**Comment by phendan** [comment]
Another note though: just noticed that the red close icon now no longer has the dark dot in the middle to indicate that there are unsaved changes. I'm not sure if that's intentional or not.

**Comment by j-f1** [comment]
Can you push the updated code to GitHub, @knopp?
