### ISSUE TITLE
Compatibility with VS Code 1.64.0

### ISSUE THREAD

**Issue by andreiborisov** [iocave/customize-ui#121]
1.64.0 seemed to introduce significant changes for the sidebar, which broke `customizeUI.activityBar` setting:

![CleanShot 2022-02-05 at 17 07 42@2x](https://user-images.githubusercontent.com/13354491/152645246-10ae10a4-7f3d-49da-a1a8-65c53e92f85c.png)

The setting is set to `wide` here.

**Comment by knopp** [comment]
Indeed, there has been quite large changes. I've adapted customize UI to them, but it seems that the `wide` settings has regressed.

**Comment by knopp** [comment]
Please let me know if this problem persists once 0.1.58 gets online (should be in few minutes).

**Comment by andreiborisov** [comment]
Fixed beautifully! Thank you🙏
