### ISSUE TITLE
CSS loading no longer working with Insiders

### ISSUE THREAD

**Issue by j-f1** [iocave/customize-ui#128]
It seems like injecting CSS is no longer working in the latest Insiders (1.65.0-insider, Commit: https://github.com/microsoft/vscode/commit/86200d542474b26aa28034e0fd5789c45c747d8b)

**Comment by knopp** [comment]
Can you let me know if this persists with 0.1.59?

**Comment by j-f1** [comment]
Fixed! Thanks for the rapid response.
