### ISSUE TITLE
customizeUI.listRowHeight not working for activity bar

### ISSUE THREAD

**Issue by mik3y64** [iocave/customize-ui#13]
Hello, thank you for creating and sharing this extension. Everything works perfectly, except for "customizeUI.listRowHeight" where it works for all listRow like "explorer view", but it doesn't work for "Source Control". The settings have no effect for "Source Control" activity bar. Is this a known issue?

**Comment by knopp** [comment]
Fixed via 9115d06ae5217c2d3387daa0efbb42b7d568c42c.
