### ISSUE TITLE
Unable to Hide Sidebar menu while using activityBar in Top position

### ISSUE THREAD

**Issue by rbreaves** [iocave/customize-ui#130]
Aka if you have this in your settings.json file
```
{
    "customizeUI.activityBar": "top"
}
```

And then press Ctrl-b to hide your sidebar you will see your menubar and activitybar disappear, but not the sidebar and then you will not be able to bring back the menubar or activitybar until you close and reopen it. This was not happening back w/ the initial PR merge 
https://github.com/iocave/customize-ui/pull/80. I do not know if it might be related to the PR merge from 12 days ago https://github.com/iocave/customize-ui/pull/90, I think it was happening to me earlier and I assumed it was some config I had done, but I have completely removed VSCode and all extensions and config files and started fresh with ONLY Customize UI installed and the bug is most certainly in the latest builds.

To get an error message about it you can also do Ctrl+Shift+P -> type/select "focus activity bar" -> errors with "invalid grid element". Any ways I hope you get this resolved!

**Comment by knopp** [comment]
https://github.com/iocave/customize-ui/commit/52b9b365441a5ae0888d56dc46588965390bdd9a should fix the hiding, but new version hasn't yet been released.

**Comment by rbreaves** [comment]
Will close! Thanks for such an awesome extension!
