### ISSUE TITLE
VS Code 1.66 Compatibility

### ISSUE THREAD

**Issue by juliand665** [iocave/customize-ui#133]
It looks like VS Code 1.66 broke this extension:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/827762/160960475-d6633d10-9879-4e81-bccb-e0924b15ffca.png">

The sidebar title (or tabs, if the sidebar is hidden) overlays the OS buttons, but that's not the main issue, which is that you can no longer drag the window around by empty space in the tab bar.

**Comment by nabsiddiqui** [comment]
+1

**Comment by knopp** [comment]
Please let me know if this persists for you once 0.1.61 gets published (should be in few minutes).

**Comment by kidonng** [comment]
@knopp 0.1.61 works well, thanks for the prompt update!
