### ISSUE TITLE
Doesn't work in 1.70.0

### ISSUE THREAD

**Issue by albert-ying** [iocave/customize-ui#145]
The "frameless" and many other settings no longer works in 1.70.0

**Comment by knopp** [comment]
Can you retest this once monkey-patch 0.1.19 and customize ui 0.1.62 become available?

**Comment by albert-ying** [comment]
@knopp thank you for the quick response, I just updated both -- it still doesn't work.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/59846322/183216807-1dff3c0d-554d-4f80-8200-356e3d104193.png">

**Comment by knopp** [comment]
Did you quit and restart VSCode? It make take couple of restarts for all the files to update.

**Comment by knopp** [comment]
Also I just published 0.1.63 (becuase for some reason 0.1.62 got published with node modules included) but I don't think that should make much difference.

**Comment by albert-ying** [comment]
Yes I did manually restart, but it doesn't change anything tho. In previous versions, if I change the customizeUI-related settings, I receive a pop-up notification that asks me to restart. This doesn't happen anymore after I update to 1.70.0

**Comment by knopp** [comment]
Do you get the "Disable / Enable monkey patch" actions in the command palette?

**Comment by EXHades** [comment]
Will it be related to `"window.experimental.useSandbox": true`?

**Comment by knopp** [comment]
I tried enabling and disabling the sandbox - it made no difference. If you try running vscode from terminal are there any error messages in the output? Are there any errors in the Extensions and Extensions Host logs?

**Comment by albert-ying** [comment]
No, there is no error when I run `code` in the terminal. Also no error in the log. I have the "Disable / Enable monkey patch" actions, but toggling them doesn't make any difference.

I also tried to reinstall the vscode, and comment out all other configurations in the setting.JSON, but still doesn't make any difference.

There is also no error in log..

```
[2022-08-06 15:23:15.305] [exthost] [info] ExtensionService#_doActivateExtension iocave.monkey-patch, startup: true, activationEvent: '*', root cause: iocave.customize-ui
[2022-08-06 15:23:15.626] [exthost] [info] ExtensionService#_doActivateExtension iocave.customize-ui, startup: true, activationEvent: '*'
```

Strange -- does it work on other people's machine?

**Comment by y1n0** [comment]
It does not work for me either. i have the version 1.70.0

**Comment by ErikHumphrey** [comment]
Not experiencing this issue on macOS; I had to restart Code twice, but got the dialog to re-apply Monkey Patch changes and restart VS Code. Using `inline`/`bottom`/`under-panel` just fine.

**Comment by albert-ying** [comment]
An complete uninstall and reinstall fixed the problem

**Comment by y1n0** [comment]
the problem for me was that i was not seeing the monkey patch prompt for apply and reload because I had do not disturb mode enabled 🤦🏼‍♂️
