### ISSUE TITLE
Activity Bar no longer at the bottom

### ISSUE THREAD

**Issue by steakscience** [iocave/customize-ui#15]
Did this recently break? I am on regular stable VS Code and it used to work but now it's back to the regular VS Code UI
![image](https://user-images.githubusercontent.com/2727095/70111327-6db08300-1684-11ea-9566-880cafbcf41e.png)

**Comment by knopp** [comment]
Not that I know of. I tested 0.1.27 with vscode 1.40.2 and I can't reproduce any issues.

**Comment by steakscience** [comment]
I'm on the same versions, this is my settings.json:
```
"workbench.enableExperiments": true,
"workbench.useExperimentalGridLayout": true,
"workbench.tips.enabled": false,
"customizeUI.activityBar": "bottom",
"window.titleBarStyle": "native",
"customizeUI.titleBar": "inline"
```

**Comment by knopp** [comment]
Is this on a Mac? If so, do other customize UI settings (i.e. "customizeUI.titleBar": "inline") work?

**Comment by steakscience** [comment]
On Mac.

It used to work! But also don't work anymore

**Comment by knopp** [comment]
Does it make any difference if you disable and re-enable monkey path?

(Disable Monkey Patch command, restart VSCode, and then Enable Monkey Patch command)

**Comment by steakscience** [comment]
@knopp That fixed it, thank you!
