### ISSUE TITLE
Bring activityBar style from vscode-titlebar-less-macos as option to customize-ui

### ISSUE THREAD

**Issue by lehni** [iocave/customize-ui#17]
First of all, congrats on making this extension! I have started using it since porting my `vscode-titlebar-less-macos` extension  to the newVSCode would represent a massive rewrite.

One thing I am missing though is the style of the activity-bar on the side (reminiscent of how Slack handles the UI), and I was wondering if we could work together on bringing this to `customize-ui`?

I would suggest adding a third option for `"customizeUI.activityBar"`, perhaps called `"left-extended"` or `"left-unifed"`? It would then have to take on the width of `--traffict-lights-width`, and extend all the way to the top:

<img width="822" alt="preview" src="https://user-images.githubusercontent.com/213275/71087513-a2e8c500-219c-11ea-98b3-77ac0ccd0a59.png">

I would then discontinue the extension and recommend `customize-ui` instead.

**Comment by knopp** [comment]
Hi,

I just published 0.1.29, it adds `wide` option to `customizeUI.activityBar` setting. Let me know if it does what you want it to.

I wanted to avoid including `left` in the name, as with this on, the activity bar will be wide regardless of whether the sidebar is on left or right.

**Comment by lehni** [comment]
Wow, you work fast! This is perfect, exactly what I was looking for, thank you!

**Comment by lehni** [comment]
For the record: With these settings, I get the same behavior as `vscode-titlebar-less-macos`:

```json
    "window.titleBarStyle": "native",
    "customizeUI.titleBar": "inline",
    "customizeUI.activityBar": "wide",
```

**Comment by lehni** [comment]
One detail that my extension was solving: When zooming in, the bar goes too wide:

![image](https://user-images.githubusercontent.com/213275/71103855-23b6b980-21bb-11ea-8218-c456593a61c7.png)

I used to do this to correct that:

```js
var factor = ${browser}.getZoomFactor();
var width = 78 / factor;
var height = 35 / factor;
```

**Comment by knopp** [comment]
I'm aware of zooming issue. It will correct itself after reloading window. The width is dependent on zoom factor, but the layout is not updated when changing zoom.

**Comment by lehni** [comment]
Oh I see. I guess you could listen to the zoom even itself and update the sizes then, but it may not be worth the effort.

**Comment by lehni** [comment]
@knopp for better alignment of the badge in wide mode, I recommend adding this styling:
```css
monaco-workbench .activitybar > .content :not(.monaco-menu) > .monaco-action-bar .badge .badge-content: {
  left: calc(50% + 0.5em);
  right: auto;
}
```

I'm currently doing so through `"customizeUI.stylesheet"`:

```json
  "customizeUI.stylesheet": {
    ".monaco-workbench .activitybar > .content :not(.monaco-menu) > .monaco-action-bar .badge .badge-content": "left: calc(50% + 0.5em); right: auto;"
  },
```

**Comment by knopp** [comment]
Thanks. I've added it https://github.com/iocave/customize-ui/commit/6e08c7bdb8bfcc35c78217e9be046195fd9cb0b4

**Comment by lehni** [comment]
Perfect, thank you!

**Comment by knopp** [comment]
Can you try 0.1.30 (should be published soon) and let me know if it works for you?

**Comment by lehni** [comment]
Yes i just did, works as expected. 🎉 

![image](https://user-images.githubusercontent.com/213275/71264689-ef6f0480-2344-11ea-90a4-ff8f37cf2181.png)

**Comment by lehni** [comment]
I have deprecated and archived this now: https://github.com/lehni/vscode-titlebar-less-macos

**Comment by adrusi** [comment]
The activity bar seems to no longer be centered under the traffic light, I've added this to my stylesheet to achieve the look in the screenshots in this thread:

```json
".monaco-workbench .activitybar>.content :not(.monaco-menu)>.monaco-action-bar .action-label.codicon": "width: 100%"
```

**Comment by lehni** [comment]
@adrusi see here: https://github.com/iocave/customize-ui/issues/94#issuecomment-840589774
