### ISSUE TITLE
Broke with VS Codium `1.77.0.23090`

### ISSUE THREAD

**Issue by andreiborisov** [iocave/customize-ui#170]
The custom build of Monkey patch seems to work still, but Customize UI settings no longer change anything in the UI.

**Comment by ghost** [comment]
Same here. @daiyam Is it mangled again?
@knopp @lehni please look into this.

**Comment by daiyam** [comment]
The Insiders version was fine so far. I've haven't check on that build. (about the mangling)

Edit: I've checked, VSCodium 1.77.0 isn't mangled.

**Comment by lehni** [comment]
I don't have time right now to look into this but will check later next week. I did see that it's not entirely broken, some features of CustomizeUI do get applied. I also saw an error in the console. I'd imagine it's just that CSS / JS has changed and the patch doesn't have the same effect anymore. I'm not a maintainer of CustomizeUI and am not familiar with its internals.

**Comment by lehni** [comment]
I've debugged and fixed this now. For now I'll just recommend installing the extensions from the attached VSIX files. Perhaps I'll decide to keep a fork of monkey-patch and customize-ui maintained under a new namespace, just for VSCodium, we shall see. Enjoy!

[customize-ui-0.2.0.vsix.zip](https://github.com/iocave/customize-ui/files/11201547/customize-ui-0.2.0.vsix.zip)
[monkey-patch-0.2.0.vsix.zip](https://github.com/iocave/customize-ui/files/11201549/monkey-patch-0.2.0.vsix.zip)

**Comment by lehni** [comment]
To avoid confusion, I've updated the version numbers to the next minor version.

**Comment by andreiborisov** [comment]
Works like a charm! Thank you @lehni! 🫶🏻

**Comment by backermanbd** [comment]
> Works like a charm! Thank you @lehni! 🫶🏻

Not working on windows :(
@andreiborisov are you a mac guy?

**Comment by ghost** [comment]
In more recent updates, specifically version 1.77.3.23102, the patch you have provided appears to be ineffective, @lehni.

**Comment by lehni** [comment]
@backermanbd I'm on 1.77.3. 23102 and it works perfectly for me. What are you seeing?

**Comment by ghost** [comment]
Apologies for the inconvenience.

Initially, when I uninstalled the `customize ui` extension and installed your patched version, it didn't seem to function correctly. However, after performing a complete reinstallation and clearing all caches, the issue has been resolved and the patched version is now operational.

**Comment by lehni** [comment]
Interesting, I had the same problem happening too. It may be that the previous version has left the app in a broken state when it started failing.

**Comment by daiyam** [comment]
Maybe in the UI db `state.vscdb`?

**Comment by lehni** [comment]
I think it's related to leaving the patched and unpatched backup files in a a state of mess.

**Comment by zisra** [comment]
@lehni Sorry for bothering, I installed both your custom extensions but nothing seems to have changed 
<img width="1030" alt="Screenshot 2023-04-28 at 9 19 41 AM" src="https://user-images.githubusercontent.com/100528712/235173233-a1519d9a-ec27-47b3-99fb-d1da23a454ee.png">

**Comment by lehni** [comment]
A little heads up to everybody interested that the new APC extension now offers a viable path forward, see: 

https://github.com/drcika/apc-extension/issues/52
