### ISSUE TITLE
Traffic lights on top of tab title when tab bar is invisible

### ISSUE THREAD

**Issue by burknator** [iocave/customize-ui#19]
Using these settings, the traffic lights are on top of the tab title, as seen in the screenshot.

```json
"workbench.editor.showTabs": false,
"window.titleBarStyle": "native",
"customizeUI.titleBar": "inline",
```
<img width="256" alt="Bildschirmfoto 2019-12-23 um 10 02 53" src="https://user-images.githubusercontent.com/26658/71348105-13f8f580-256c-11ea-9f86-80731f3b2e47.png">

**Comment by knopp** [comment]
Thank you for the report. Can you test this once 0.1.31 gets published and let me know if it is any better?

**Comment by burknator** [comment]
Wow! That was fast! The issue has been fixed, thanks!
