### ISSUE TITLE
Can I change the font of textbox only?

### ISSUE THREAD

**Issue by shungo27** [iocave/customize-ui#2]
Can I change the font of textbox only?

![input](https://user-images.githubusercontent.com/7065076/62003265-7da4dd00-b14f-11e9-8d41-c02b01021492.png)

**Comment by knopp** [comment]
You should be able to do this by specifying custom CSS using "customizeUI.stylesheet":, i.e
```json5
"customizeUI.stylesheet": {
   ".monaco-inputbox": "font-family: courier new !important; font-size: 30px !important;",
}
```

Note that this will only change font in some fields, there are more selectors needed. You can use inspect element from developer tools to find the selectors;

**Comment by shungo27** [comment]
Thank you for your information. I solved it with CSS below.

```
"customizeUI.stylesheet": {
	".monaco-inputbox, .monaco-inputbox .input, .suggest-input-container .mtk1, .monaco-select-box": "font-family: 'Ricty Diminished' !important; font-size: 15px !important;"
}
```
