### ISSUE TITLE
Targeting UI elements in Zen Mode?

### ISSUE THREAD

**Issue by BrianD91** [iocave/customize-ui#20]
I have the following in my settings:

`    "customizeUI.stylesheet": {
      ".editor-actions": "display: none !important;",
    },`

And the setting gets rid of the editor actions, but they re-appear in zen mode, which is more specifically where I don't want them. How can I select those elements to not display when zen mode is active?

**Comment by BrianD91** [comment]
I was able to resolve this by adding  `".monaco-toolbar": "display: none !important;"` to the customizeUI stylesheet

**Comment by BrianD91** [comment]
Hmm,  well that _does_ solve the zen mode display issue. Is there a way to get that to ONLY work in zen mode?

**Comment by knopp** [comment]
I don't think there's a selector specifically or zen mode, but try this:
`".nopanel.nosidebar.nostatusbar.fullscreen .monaco-toolbar" : "display:none",`
