### ISSUE TITLE
Is it possible to make "wide" option of activity bar, a little less wide

### ISSUE THREAD

**Issue by chethankumar** [iocave/customize-ui#21]
I like the wide option of the activity bar which includes traffic lights. But, could you make a compressed version of it. Something similar to slack. Wide, but bit more compressed.

**Comment by knopp** [comment]
Slack is indeed slightly narrower, as it uses "regular" traffic light buttons, not the offset ones. However I don't currently have plans introducing another variable. The current wide option was included to add parity with not defunct [titlebar-less extension](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-titlebar-less-macos). If screen estate is a problem, you can just use "bottom" to move the activity bar below sidebar.
