### ISSUE TITLE
Monkey Patch failed: Error: User did not grant permission.

### ISSUE THREAD

**Issue by marcelloinfoweb** [iocave/customize-ui#22]
Monkey Patch failed: Error: User did not grant permission.

OS: Zorin 15 Core

**Comment by knopp** [comment]
Do you have access to patch vscode? Is it running from actual folder on your drive, or from read-only image?

**Comment by marcelloinfoweb** [comment]
I installed via snap

**Comment by knopp** [comment]
Customize-ui needs to modify vs-code installation and there's no way to patch a read-only snap image. So this can't work.
