### ISSUE TITLE
Can I Use Multiple Columns?

### ISSUE THREAD

**Issue by KiraiEEE** [iocave/customize-ui#25]
Can I Use Multiple Columns When Settings Activitybar To Bottom ?
If Not Please Add It As Feature 😉
![キャプチャ](https://user-images.githubusercontent.com/54278089/73132932-1b576700-4022-11ea-9414-a022da662e27.PNG)

**Comment by knopp** [comment]
Can you be more specific? More columns where?

**Comment by joshmeads** [comment]
@knopp I imagine he means stacking the icons into multiple rows instead of truncating. At least that's what I'd personally find very useful.

![Screenshot 2020-02-05 at 12 36 34 PM](https://user-images.githubusercontent.com/8870827/73880938-46a53780-4814-11ea-986f-374ad7a43a95.png)
