### ISSUE TITLE
customizeUI.listRowHeight - icons too big to fit

### ISSUE THREAD

**Issue by rustemkk** [iocave/customize-ui#26]
Hello!

I'm using this setting: `"customizeUI.listRowHeight": 16,` and for some icons pack it looks fine:
Seti:
![image](https://user-images.githubusercontent.com/5126284/74404338-38ba6c80-4e3b-11ea-942b-cce4250c564e.png)

But most of icon packs get cut off on the bottom:
Field Lights:
![image](https://user-images.githubusercontent.com/5126284/74404426-86cf7000-4e3b-11ea-8b7c-84da8b86f0dd.png)
Webstorm Icon Theme:
![image](https://user-images.githubusercontent.com/5126284/74404412-7a4b1780-4e3b-11ea-83c0-f20cb2c6e890.png)

Is it possible to solve (shrink icons a little bit) with some `customizeUI.stylesheet`? Or somehow by configuring and building my own icons pack (https://github.com/rustemkk/vscode-jetbrainish-icons)?

**Comment by forivall** [comment]
Yup!
```
"customizeUI.stylesheet": {
    ".monaco-icon-label:before": "height: 16px;"
  },
```

**Comment by rustemkk** [comment]
@forivall Yesss, thank you!
