### ISSUE TITLE
Doesnt work VSCode v1.37.0 July 2019 update

### ISSUE THREAD

**Issue by gee-forr** [iocave/customize-ui#3]
Hi there,

I've been using this great extension for a while now, and recently updated my VSCode to 1.37.0. Unfortunately, it doesn't seem to work. My VSCode now looks like this when Customize UI is activated.

Here's my VSCode version data:
```
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

I'm running CustomizeUI 0.1.16 and Monkey patch 0.1.6

![Screenshot 2019-08-12 at 08 33 45](https://user-images.githubusercontent.com/345730/62848608-b068dc80-bcdc-11e9-8737-befb5fdab7bf.png)

**Comment by knopp** [comment]
This is weird, I'm always testing with nightly so something like this shouldn't happen. It looks like maybe the grid is deserialized in weird state. You can try shutting down vscode and removing the following files:

`~/Library/Application Support/Code/User/globalStorage\state.vscdb` and
`~/Library/Application Support/Code/User/globalStorage\state.vscdb.backup` if exists

If that doesn't help, please give me customize-ui settings that you uses. Also please note that currently action bar on bottom only works in default settings (panel on bottom, sidebar on left)

**Comment by knopp** [comment]
Alternatively, if you don't want to remove entire file, you can open it with any sqlite browser/editor and remove the row from `itemTable` with key `workbench.grid.layout-bottom-activity-bar`. But in my experience the file mostly contains UI state.

**Comment by gee-forr** [comment]
Hi @knopp thanks for the help, but unfortunately, it didn't work :( Here's my settings:

![image](https://user-images.githubusercontent.com/345730/62852271-3ee35b00-bce9-11e9-9306-4868bf79487f.png)

**Comment by knopp** [comment]
Do you have panel on the right? That might break `"customizeUI.activityBar": "bottom"`. Right now it can be either panel on right or activity bar on bottom. There have been many changes recently to the experimental grid layout in vscode and it's quite difficult to keep up, so I don't plan supporting non default configurations (i.e. panel on right) alongside bottom activity bar at least until things settle down a bit with the grid.

**Comment by gee-forr** [comment]
No panels on the right. I do have a terminal on the right, but that's always worked perfectly.

**Comment by knopp** [comment]
Terminal is part of panel. If you have terminal on the right, it means that you have panel on the right. Again, `"customizeUI.activityBar": "bottom"` right now doesn't work with panel (terminal) on the right.

> always worked perfectly with customize UI

Unfortunately that doesn't mean much. Moving activity bar to bottom relies on experimental grid layout, and there have been big changes recently in vscode regarding the way grid layout works and customize ui doesn't yet accomodate all configurations. There are plans to do that, but I'm waiting for things to settle down a bit because right now it changes too quickly.

**Comment by knopp** [comment]
I just pushed 0.1.17 which supports sidebar and panel on right, however only for **vscode insider builds**.

 That said, I would not recommend using customize-ui with insider builds right now, as there seems to be quite a lot of work being done on workbench grid layout and it breaks customize ui frequently.

**Comment by gee-forr** [comment]
hi @knopp - oh wow - thank you! I'll wait until next month, when the insider changes make their way to vanilla vscode.

Thank you so much!

**Comment by knopp** [comment]
Should now work after 1.38.0 update.

**Comment by gee-forr** [comment]
Can confirm this is working again. Thank you so much :)
