### ISSUE TITLE
CustomiseUI breaks source control providers pane

### ISSUE THREAD

**Issue by betterthanclay** [iocave/customize-ui#35]
When active, the extension causes the "Source Control Providers" pane to never be rendered under the SCM side bar. The indexing of the remaining panes in the SCM view is then off by one which causes unexpected behaviour when trying to show / hide providers in the list.

This image shows with the extension disabled (expected behaviour):
![disabled](https://user-images.githubusercontent.com/1273586/76327840-6b447180-62e2-11ea-883d-ef7c06da35ff.png)

This image show with the extension enabled:
![enabled](https://user-images.githubusercontent.com/1273586/76327891-7bf4e780-62e2-11ea-8f44-ee6daf62da24.png)

Clicking the first provider in the dropdown in the second image would incorrectly hide the **second** provider in the panel.

**Comment by knopp** [comment]
I've pushed 0.1.33, can you give it a go and let me know if it fixes the problem for you?

**Comment by betterthanclay** [comment]
That's awesome, thank you - it appears to have fixed the problem.
I'll give a proper test this evening and let you know if there are any quirks.
