### ISSUE TITLE
Customize-UI not working with current Vscode version

### ISSUE THREAD

**Issue by Sylenss** [iocave/customize-ui#37]
Hello, Im trying to make customize-ui work and nothing taking effect with my visual studio code, Ive restarted numerous of times and nothings happening 

Heres a screenshot of the settings that im trying to configure.
![Screen Shot 2020-03-30 at 9 45 40 AM](https://user-images.githubusercontent.com/45975952/77919971-dba03c00-726b-11ea-83fb-a29f424b071b.png)

Here is the version of vscode im currently running 

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by knopp** [comment]
Why do you have customizeUI in editor.tokenColorcustomizations section? It should be top level.

**Comment by Sylenss** [comment]
Ahhh what a silly mistake sorry about that.. My God!
