### ISSUE TITLE
Title Action Icons cramped to top

### ISSUE THREAD

**Issue by manuhornung** [iocave/customize-ui#42]
When running this extension on Linux (Manjaro 20 Gnome), the action icons on the top right of the editor pane become much smaller in height and move too far up in the toolbar:
![image](https://user-images.githubusercontent.com/4516798/81161696-425ff600-8f8c-11ea-8d14-83efcd6966db.png)

I believe this is due to a missing selector in the styles that should only apply when the mac OS inline title bar is active

**Comment by knopp** [comment]
Thanks. I published 0.1.37, should be live in few minutes, let me know if it fixes the problem.

**Comment by manuhornung** [comment]
Thanks a lot for the quick reaction! I can confirm this is fixed :)
