### ISSUE TITLE
Missing Swizzle.dylib

### ISSUE THREAD

**Issue by rmccue** [iocave/customize-ui#51]
Hi! Customize-UI isn't working for me, and the developer tools show:
```
Error: ENOENT: no such file or directory, open '/Users/rmccue/.vscode/extensions/iocave.customize-ui-0.1.41/modules/swizzle.dylib'
```

Possibly related to #49 and the changes in 0.1.41?

**Comment by rmccue** [comment]
Confirmed downgrading to 0.1.40 manually fixes this issue.

**Comment by knopp** [comment]
Right, sorry about this, can you retest once 0.1.42 gets published? (should be in 10 minutes)

**Comment by rmccue** [comment]
Updated and all looking good. Thanks!

By the way, when I make changes that require a restart, VS Code prompts me twice (actually, twice _per window), and only the second prompt has any effect. Could be a conflict with another extension though!
