### ISSUE TITLE
Title overlaps system buttons with "Title Bar: inline" on latest VS Code Insiders

### ISSUE THREAD

**Issue by aselivanov** [iocave/customize-ui#52]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/331632/83460636-9072f700-a46f-11ea-9369-9f164b29d6a0.png">

**Comment by knopp** [comment]
Please let me know if this persists after 0.1.43 goes live.

**Comment by aselivanov** [comment]
Fixed by 0.1.43.
