### ISSUE TITLE
Font name please 

### ISSUE THREAD

**Issue by johanb83** [iocave/customize-ui#55]
Hi !

I downloaded your plugin and I would like to use the same font as the one on the plugin’s presentation page.

Can you tell me the name of the editor font please ?

Thank you ! 

<img width="921" alt="Capture d’écran 2020-06-27 à 23 43 21" src="https://user-images.githubusercontent.com/60623961/85932912-26fcd180-b8d1-11ea-98d7-321ec0970115.png">

**Comment by knopp** [comment]
The font is Fira Code

https://github.com/tonsky/FiraCode

**Comment by johanb83** [comment]
Thank you so much Matej ! :)


Le mer. 1 juil. 2020 à 23:16, Matej Knopp <notifications@github.com> a
écrit :
