### ISSUE TITLE
Inline titlebar overlaps system buttons

### ISSUE THREAD

**Issue by aselivanov** [iocave/customize-ui#58]
It is like that again.
![image](https://user-images.githubusercontent.com/331632/87660265-77947b80-c767-11ea-8ddb-a4197ab762a2.png)

**Comment by knopp** [comment]
This is caused by new vscode loader in insiders. In general using insiders with customize-ui might not be the best idea.

I've pushed monkey-patch extension update. Try restarting vscode and let me know if the problem persists.

**Comment by aselivanov** [comment]
It's fixed now.

**Comment by aselivanov** [comment]
I think this is relevant again, as of Insiders build.

**Comment by knopp** [comment]
Pushed 0.1.49. Please let me know if the problem persists.

**Comment by aselivanov** [comment]
Good now. Thanks!
