### ISSUE TITLE
Customize UI keeps closing "Terminal Panel" 

### ISSUE THREAD

**Issue by filikos** [iocave/customize-ui#61]
When having customize-ui activated the "D-Panel" -> [https://code.visualstudio.com/docs/getstarted/userinterface](url)
gets closed if I switch the tab to "Terminal" 

Settings.json
```JSON
.
.
.
"customizeUI.activityBar": "bottom",
  "customizeUI.fontSizeMap": {
    "10px": "11px"
  },
.
.
.
```

Not sure if this is an customize-ui or Monkey Patch issue, if you need more information please let me know.

**Comment by knopp** [comment]
This would be a customize-ui issue, but I'm not sure how to reproduce it.

**Comment by NikoFilippidis** [comment]
Maybe the list of all my current plugins, maybe there is an conflict with another extension. I removed Customize UI temporary.

```JSON
42Crunch.vscode-openapi
766b.go-outliner
Arjun.swagger-viewer
burkeholland.simple-react-snippets
ckolkman.vscode-postgres
dracula-theme.theme-dracula
esbenp.prettier-vscode
formulahendry.code-runner
golang.go
iocave.monkey-patch
k--kato.intellij-idea-keybindings
premparihar.gotestexplorer
redhat.vscode-yaml
shd101wyy.markdown-preview-enhanced
zenor.makefile-creator
```
settings.json
```JSON
{
  "window.zoomLevel": 2,
  "workbench.colorTheme": "Dracula",
  "go.formatTool": "gofmt",
  "editor.formatOnSave": true,
  "go.useLanguageServer": true,
  "go.lintTool": "golangci-lint",
  "swaggerViewer.previewInBrowser": true,
  "files.autoSave": "afterDelay",
  "terminal.integrated.shell.osx": "/bin/zsh",
  "workbench.activityBar.visible": true,
  "workbench.tree.indent": 10,
  "workbench.colorCustomizations": {
    "tree.indentGuidesStroke": "#f5f5f5"
  },
  "editor.columnSelection": false,
  "editor.rulers": [80],
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "emmet.extensionsPath": "",
  "task.problemMatchers.neverPrompt": null
}

```
Software Versions: 

- VS Code: 1.48.0
- MacOS: 10.15.6

So far I dont use any other extension which would be affecting windows within VS Code, I hope this helps to solve this issue.

**Comment by knopp** [comment]
Is your panel at the bottom? Can you post screenshot of your vscode?

**Comment by filikos** [comment]
@knopp  Sorry for my late reply, with VS Code v1.49.2 I can't replicate the bug, I guess this is fixed.
