### ISSUE TITLE
customizeUI.listRowHeight breaks icons.

### ISSUE THREAD

**Issue by nrthbound** [iocave/customize-ui#67]
When setting `customizeUI.listRowHeight`, it breaks the alignment of icons and text. Using it with `30` and the icons are higher than the text.

**Comment by rustemkk** [comment]
Hey, @nrthbound, I using this additional setting:
```
  "customizeUI.stylesheet": {
    ".monaco-icon-label:before": "margin-top: 3px;"
  },
```
Hope it helps to you as well 😉
