### ISSUE TITLE
Could you add Vibrancy?

### ISSUE THREAD

**Issue by Superpencil** [iocave/customize-ui#7]
I made a small PR to add vibrancy that got rejected but seems like would be a good fit here:
https://github.com/microsoft/vscode/pull/65215

**Comment by knopp** [comment]
Thanks for the suggestion. I played with it, but unfortunately it does seem to have detrimental effect on performance when enabled (4k retina screen). I think the issue might be that the underlying NSVisualEffectView stretches entire window, which is a massive overhead, especially when only using actual blur on sidebar.

**Comment by Superpencil** [comment]
Yeah, there's no way to 'localize' it though, it's either full window is transparent or nothing, I have some other electron apps that are transparent and they all perform worse than without...
