### ISSUE TITLE
"customizeUI.titleBar": "inline" is broken on 1.53.0

### ISSUE THREAD

**Issue by dschuessler** [iocave/customize-ui#79]
See the upper left.

![Bildschirmfoto 2021-02-08 um 12 28 26](https://user-images.githubusercontent.com/5774545/107213942-74b1ee80-6a09-11eb-9db2-aa07f0c1270c.png)

**Comment by knopp** [comment]
I can't seem to reproduce this with 1.53 or insiders. Is this with Customize UI 0.1.50 ?

**Comment by dschuessler** [comment]
That was it. I was still on 0.1.49. Upgrading to 0.1.50 fixed it. Thanks!
