### ISSUE TITLE
Tab dragged to the left to form an editor group is obscured by traffic lights if side bar is closed

### ISSUE THREAD

**Issue by krupenja** [iocave/customize-ui#8]
1. Enable `"customizeUI.titleBar": "inline",`
2. Make sure that sidebar and activity bar are hidden.
3. Have at least two tabs open in a *single* editor group.
4. Drag one of the tabs to the left to form an editor group.

The tab in the new editor group is behind the traffic lights controls.
![output](https://user-images.githubusercontent.com/26354715/66481204-070a5100-eaa9-11e9-8686-e278023cee3d.gif)

After completing the steps, opening side bar and closing it again resolves the issue.

**Comment by knopp** [comment]
Indeed. Thanks for the report. Looks like the margin is not properly updated when this happens. It might be tricky to fix. In any case, temporarily showing and hiding the sidebar (cmd+b) resets the margin.

**Comment by krupenja** [comment]
Confirming that the issue is fixed after updating extension. Thank you for the quick fix!
