### ISSUE TITLE
VSCode 1.55 - activity bar doesn't shows only 1 icon though there's enough space

### ISSUE THREAD

**Issue by ronakg** [iocave/customize-ui#87]
I have the activity bar set to the bottom. In VSCode version 1.55, only 1 icon shows up along with a 3-dot menu to get to other icons on the activity bar.

See the screenshots.

![image](https://user-images.githubusercontent.com/1058322/113193644-0c1b0d00-9215-11eb-8855-cde7cedc9c0e.png)

![image](https://user-images.githubusercontent.com/1058322/113193823-42f12300-9215-11eb-8d30-f0d935111e60.png)

Changing the sidebar position to either left or right does not make any difference. The issue is still there.

Setting `customizeUI.activityBarHideSettings` to `true` or `false` doesn't make any difference either.

My settings for customize UI:

```json
    "customizeUI.activityBar": "bottom",
    "customizeUI.titleBar": "inline",
```

**Comment by knopp** [comment]
Can you try 0.1.52 once it is published and let me know if the problem persists?

**Comment by ronakg** [comment]
Sure, still seeing 0.1.51 on the marketplace.

**Comment by knopp** [comment]
It usually takes couple of minutes.

**Comment by ronakg** [comment]
0.1.52 fixed the issue. Thanks for the quick turnaround. (y)
