### ISSUE TITLE
VSCode Version: 1.55.0 - breaks sidebar search and other functions

### ISSUE THREAD

**Issue by vvvlad** [iocave/customize-ui#88]
When Activity Bar setting is set to top or bottom, sidebar is not working correctly:
1. On load, shows empty, and only after one of the buttons clicked populates with content.
2. Search in extensions in not returning any results.
3. Debug toolbar in floating mode disappears.

This started only after latest VSCode update.
Isolated the source of the issue by removing the extension.
Also, when changing the Activity Bar setting to regular or wide, all functions as expected.

VSCode Version: 1.55.0
MacOS BigSur

**Comment by trazyn** [comment]
same here

**Comment by knopp** [comment]
Please let me know if the problem persists once 0.1.53 is published (should be in few minutes)

**Comment by trazyn** [comment]
@knopp  0.1.53 is working fine 👍

**Comment by vvvlad** [comment]
@knopp  for me as well, seems like it fixed the issues.
Thanks!!!
