### ISSUE TITLE
Cant put activity bar at the bottom anymore

### ISSUE THREAD

**Issue by ignism** [iocave/customize-ui#9]
I've been unable to relocate my activity bar to the bottom since 1.39. Restarting or re-enabling the monkey patch has no effect.

**Comment by knopp** [comment]
I regularly test this with latest vscode and vscode-insiders. I'm not quite sure what's wrong with your case, can you check that you have "workbench.useExperimentalGridLayout" set to `true`?

**Comment by ignism** [comment]
That did the trick, I had to add it manually. Clicking the "enable" button on the notification apparently did nothing. On a side note: vscode doesn't seem to recognize, even though it works?
It does not autocomplete it and it is greyed out. Thanks anyway!

**Comment by knopp** [comment]
I think it doesn't autocomplete because there it's already somewhere else in the settings file.
