### ISSUE TITLE
Cannot Change Font for Context Menu

### ISSUE THREAD

**Issue by TimilsinaBimal** [iocave/customize-ui#93]
I applied custom font through CSS to the body. Almost all the parts works except the context menu of the editor.   
My Setting is:
```
"customizeUI.font.regular": "SF UI Display Medium",
    "customizeUI.fontSizeMap": {
        "13px": "14px",
        "12px": "14px",
        "window-title": "15px", // Window title font when using custom titlebar
        "tab-title": "14px", // Used for editor tab titles
        "monospace": "14px", // Used for monospace fonts in user interface
        "menu": "14px",
    },
```
So, Is there any way to change the font of the right context menu in the editor too?
The Right Context menu of the file explorer works fine but not of the editor.

**Comment by TimilsinaBimal** [comment]
Here is the photo:
![Screenshot (59)](https://user-images.githubusercontent.com/45899783/118126378-f6a22100-b417-11eb-9b90-3c545ba77c3b.png)

**Comment by j-f1** [comment]
At least on macOS, VS Code uses the native context menu functionality. This means you have no control over the styling of the menus.

**Comment by TimilsinaBimal** [comment]
What about windows. I don't think VS code uses Os's context menu in windows, since, when I open context menu in explorer menu(side bar), the font works fine, but not  on Editor menu..

**Comment by srisar** [comment]
Hi, Did you find a solution on Windows? I am trying to find a way to change the context menu font as well.
